sources:
  - name: OpenapiApi
    handler:
      openapi:
        endpoint: https://petstore3.swagger.io/api/v3
        source: https://petstore3.swagger.io/api/v3/openapi.json
transforms:
  - rename:
      mode: bare | wrap
      renames:
        - from:
            type: Query
            field: getPetById
          to:
            type: Query
            field: getPetByIdTest